// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/ad3n/golang-testable/models"

	mock "github.com/stretchr/testify/mock"
)

// AccountRepository is an autogenerated mock type for the AccountRepository type
type AccountRepository struct {
	mock.Mock
}

// Find provides a mock function with given fields: Id
func (_m *AccountRepository) Find(Id int) (*models.Account, error) {
	ret := _m.Called(Id)

	var r0 *models.Account
	if rf, ok := ret.Get(0).(func(int) *models.Account); ok {
		r0 = rf(Id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(Id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Saves provides a mock function with given fields: accounts
func (_m *AccountRepository) Saves(accounts ...*models.Account) error {
	_va := make([]interface{}, len(accounts))
	for _i := range accounts {
		_va[_i] = accounts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...*models.Account) error); ok {
		r0 = rf(accounts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
